### ISSUE TITLE
Glyphicons are not displayed in the Sharing View.

### ISSUE THREAD

**Issue by tkhsknsk** [s-tip/stip-gv#11]
The following icons are not displayed on the Sharing view.

- trash bin
- CSV
 etc.

There's a pull-down menu at the top right that lets you choose a theme, such as a background.
But it doesn't seem to work for some reason.

The theme is bootswatch, so we need to check it based on this.
https://bootswatch.com/

---
Sharing画面でゴミ箱やCSVなどのアイコンが表示されない。
右上にプルダウンメニューがあり、背景などのテーマを選ぶことができるのですが、
何かしらん原因で何を選んでもデフォルトに戻ってしまうため、
テーマの切り替え部分ところから調査が必要だと思われる。
テーマにはbootswatchを使っている。

**Comment by uchimrina** [comment]
The cause of each problem is different.

1. glyphicon does not appear
2. Be unable to select themes

I want to deal with the problem of 2 as another "issue".
How do you like it?

---  
それぞれ原因は違うようです。

1.  glyphicon が表示されない
2.  テーマ選定が出来ない

2は別の issue として対応したいと思いますが、いかがでしょうか？

**Comment by stmtstk** [comment]
@uchimrina 

Good recomendation.

We should separate two issues.
We should continue to discuss about the first issue, create a new card about the second issue.

---

良い提案だと思います。
この Issue では 最初の議題のみ取り上げて進行して、2 番目は 別 card にしましょう。
対応始めたら Issue に変換してください。

**Comment by uchimrina** [comment]
Some css files are not used.
Should I delete it?

Not Used
| path | file name | version |
|:---|:---|---|
|stip-common\stip-gv\src\static\bootstrap\css|bootstrap.css|3.3.6|
|stip-common\stip-gv\src\static\bootstrap\css|bootstrap.min.css|3.3.7|
|stip-common\stip-rs\src\static\bootstrap\css|bootstrap.css|3.3.6|
|stip-common\stip-rs\src\static\bootstrap\css|bootstrap.min.css|3.3.7|

Used
| path | file name | version |
|:---|:---|---|
|stip-common\src\static\css|bootstrap.min.css|3.3.5|
|stip-common\stip-gv\src\static\bootstrap\css\cerulean|bootstrap.css|3.3.7|
|stip-common\stip-gv\src\static\bootstrap\css\\*|bootstrap.css|3.3.7|
|stip-common\stip-rs\src\static\bootstrap\css\cerulean|bootstrap.css|3.3.7|
|stip-common\stip-rs\src\static\bootstrap\css\\*|bootstrap.css|3.3.7|

**Comment by stmtstk** [comment]
@uchimrina 

Thank you for your report.
When we moved to css files from rs/gv to common, we forgot to delete duplicate css files.
We should delete those filles.

We will create another issue to resolve this issue.

**Comment by stmtstk** [comment]
I Changed a title.

---

タイトルがなんかしっくりこないので直しました。
Do not で始まると禁止の意味になるので。

**Comment by stmtstk** [comment]
@tkhsknsk @uchimrina 
Thank you for your co-operation.
