### ISSUE TITLE
I cannot select a theme on the GV Sharing page.

### ISSUE THREAD

**Issue by uchimrina** [s-tip/stip-gv#19]

**Comment by uchimrina** [comment]
I think we cannot change the theme without user.css_thema, on the sharing page.
https://github.com/s-tip/stip-gv/blob/master/src/gv/templates/nav_header.html#L59

Overwrites user information obtained by get_common_replace_dict.
Is it okay to delete it?
https://github.com/s-tip/stip-gv/blob/master/src/gv/sharing/views.py#L110


GVAuthUser has css_thema.
```
views.py#L95
	'user ': <GVAuthUser: GVAuthUser object>

views.py#L110
	'user ': <SimpleLazyObject: <STIPUser: admin>>
```

---  
sharing ページでは、user.css_thema がないことでテーマを変更できてないと思われます。
views.py#L110 で get_common_replace_dict で取得した user 情報を上書きしているのですが、削除しても大丈夫な処理でしょうか？
GVAuthUser は css_thema を持っているため、上書きされることで user.css_thema がないという状況になっています。

**Comment by stmtstk** [comment]
@uchimrina 

Thanks for your investigation. Your suggestion seems to be correct.
Delete a line #110 (and #109), and try to run.

---

調査ありがとうございます。
おそらく #110 行目の上書きが原因ですね。
外して試してみてください。で、一通りそちらの調査がおわったら pull request してみてください。
こちらでも検証します。

**Comment by stmtstk** [comment]
@uchimrina 

Thank you  for your co-operation.
