### ISSUE TITLE
If you select a theme on the top page after logging in, you will be logged out.

### ISSUE THREAD

**Issue by ta-hiroki** [s-tip/stip-gv#20]

**Comment by ta-hiroki** [comment]
@stmtstk 

The following tag is added by [getNextElement()](https://github.com/s-tip/stip-gv/blob/master/src/static/js/nav_header.js#L8) immediately after login. 
`<input type="hidden" name="next" value="/login">`

Therefore, the user is transferred to the login page.
Change [src/gv/css/views.py](https://github.com/s-tip/stip-gv/blob/master/src/gv/css/views.py) to:  
　Befor:  
<pre>next_ = get_next_location(request)
return redirect(next_)
</pre>
　After:   
<pre>next_ = get_next_location(request)  
　if next_ == '/login': 
　　next_ = '/'
return redirect(next_)  
</pre>

Is there any problem?

---

ログイン直後はテーマ変更ボタンクリック時の処理の getNextElement() でログインページの URL 情報が取得されます。
そのためログインページに遷移してしまいます。

views.py にログインページの URL が取得された場合はトップ画面に遷移させるように変更を加えます。  
問題ないでしょうか?

**Comment by stmtstk** [comment]
@ta-hiroki 

After input a username and password and submit on login page, S-TIP move to dashboard page.
And this url is http(s)://hostname:port/login.
I think this url should be http(s)://hostname:port/dashboard

---
ログイン直後の Web page の アドレスバーは http(s)://hostname:port/login となっているので、
その後に css テーマを変更すると、変更後のアドレスが  http(s)://hostname:port/login となって、
ログインページに行く。という把握しました。

で、その時に /login であれば / にするという方法もありなのですが、
あるべき姿は、

「ログインに成功したら、 http(s)://hostname:port/dashboard を表示する。」

だと思います。この状態であれば css 変更後も /dashboard にジャンプするので。

ということで認証後に /dashboard に redirect するという方法を探してもらえないでしょうか？

**Comment by ta-hiroki** [comment]
@stmtstk 

Confirmed login [process](https://github.com/s-tip/stip-gv/blob/master/src/gv/login/views.py#L42).
I can fix this problem by redirecting it to the dashboard screen.

Before: <pre>認証成功(初期画面のdashboardへredirect)
return dashboard_view_top(request)</pre>

After: <pre>認証成功(初期画面のdashboardへredirect)
 return redirect('/dashboard')</pre>

----

認証後の処理を見ると Dashbord の views.py の関数( dashboard_view_top() )を呼び出しrender 処理が実行されていました。
( dashboard_view_top() は '/dashboard' へ redirect した際にも実行される)
そのため関数を呼び出さず redirect することで対応可能だと思います。

**Comment by stmtstk** [comment]
@ta-hiroki 

Thanks for your investigaiton.
Try to fix in this way.
